# -*- coding: utf-8 -*-
"""MatPlotlib2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hu6NYEKmueI2-zcSwrSsGvgXKlT5zcPy

MATPLOTLIB

Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. It's widely used for generating plots, charts, histograms, and other graphical representations of data.

Types of Matplotlib Visualizations and Their Uses

Qualitative Visualization

1. Bar Chart

Bar charts are suitable for comparing categories of data. Each bar represents a category, and the height or length of the bar corresponds to the value it represents.
"""

from sklearn.datasets import load_breast_cancer
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Load the Iris dataset
bc = load_breast_cancer()
bc

X = bc.data          # Features
y = bc.target        # Labels (0 = malignant, 1 = benign)
feature_names = bc.feature_names
target_names = bc.target_names

# Create a DataFrame for easier exploration
df = pd.DataFrame(X, columns=feature_names)
df['target'] = pd.Categorical.from_codes(y, target_names)

# Display first 5 rows
print(df.head())

from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import numpy as np

# Load the Iris dataset
iris = load_iris()
iris

X = iris.data
y = iris.target
target_names = iris.target_names

# Bar Plot
plt.figure(figsize=(8, 6))
unique, counts = np.unique(y, return_counts=True)
plt.bar(target_names, counts, color=plt.cm.viridis(np.linspace(0, 1, len(target_names))))
plt.title('Bar Plot of Iris Species')
plt.xlabel('Species')
plt.ylabel('Count')
plt.show()

X.shape

"""**Interpretation of Bar Plot**:
   - This plot shows the frequency of each iris species in the dataset using a bar chart.
   - The x-axis represents the species (setosa, versicolor, virginica), and the y-axis represents the count or frequency of each species.
   - Each bar corresponds to one of the species, and the height of the bar indicates the number of instances of that species in the dataset.

**2. Pie Chart**

Pie charts display the proportion of each category in a dataset as slices of a circle. They are suitable for showing parts of a whole.
"""

# Pie Plot
plt.figure(figsize=(8, 6))
plt.pie(np.bincount(y), labels=target_names, autopct='%1.1f%%', startangle=120)
plt.title('Pie Plot of Iris Species')
plt.savefig('pieplot.png')
plt.show()

"""**Interpretation of the Pie Plot Chart**:
   - This plot represents the distribution of iris species in the dataset using a pie chart.
   - Each segment of the pie chart corresponds to one of the three iris species: setosa, versicolor, and virginica.
   - The size of each segment indicates the proportion of each species in the dataset.

### **Quantitative Visualization**

**3. Heatmap**

Heatmaps visualize data in a 2D grid, where colors represent the values of each cell. They are commonly used to display correlations, distributions, or densities of data points.
"""

from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import numpy as np

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target
target_names = iris.target_names

# Heatmap (Correlation Matrix)
plt.figure(figsize=(8, 6))
corr_matrix = np.corrcoef(X.T)

# Plot heatmap
plt.imshow(corr_matrix, cmap='coolwarm', aspect='auto')

# Add annotations
for i in range(corr_matrix.shape[0]):
    for j in range(corr_matrix.shape[1]):
        plt.text(j, i, f'{corr_matrix[i, j]:.2f}', ha='center', va='center', color='black')

# Add colorbar
plt.colorbar(label='Correlation Coefficient')

# Set labels
plt.xticks(ticks=np.arange(len(iris.feature_names)), labels=iris.feature_names)
plt.yticks(ticks=np.arange(len(iris.feature_names)), labels=iris.feature_names)

# Add title
plt.title('Heatmap of Correlation Matrix (Iris Dataset)')

# Show plot
plt.show()

"""**Interpretation of Heatmap (Correlation Matrix)**:
   - This plot visualizes the correlation between different features (sepal length, sepal width, petal length, petal width) in the iris dataset.
   - The x-axis and y-axis represent the features, and each cell in the heatmap represents the correlation coefficient between two features.
   - High positive correlation is indicated by lighter colors (e.g., yellow), while high negative correlation is indicated by darker colors (red).

**4. Line Plot**

Line plots are used to visualize data points connected by straight line segments. They are effective for showing trends over time or any sequential data.
"""

# Line Plot
plt.figure(figsize=(8, 6))
plt.plot(X[:, 0], label=iris.feature_names[0])
plt.xlabel('Sample Index')
plt.ylabel('Sepal Length (cm)')
plt.title('Line Plot of Sepal Length (cm)')
plt.legend()
plt.savefig('Line Plot png')
plt.show()

"""**Interpretation of Line Plot**:
   - This plot shows the trend of sepal length across the instances of the dataset.
   - The x-axis represents the index of each instance in the dataset, and the y-axis represents the sepal length in centimeters.
   - The line connects the sepal length values of consecutive instances, showing how sepal length varies across the dataset.

**5. Scatter Plot**

Scatter plots are useful for visualizing the relationship between two continuous variables. Each point represents an observation in the dataset.
"""

# Scatter Plot
plt.figure(figsize=(8, 6))
for i in range(len(target_names)):
    plt.scatter(X[y == i, 0], X[y == i, 1], label=target_names[i])
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Sepal Width (cm)')
plt.title('Scatter Plot of Sepal Length vs Sepal Width')
plt.legend()
plt.show()

"""**Interpretation of Scatter Plot**:
   - This plot visualizes the relationship between sepal length and sepal width for each iris species.
   - Each point represents an instance in the dataset, with the x-coordinate representing sepal length and the y-coordinate representing sepal width.
   - Different colors represent different species, allowing us to see how sepal length and width vary between species.

**6. Box Plot**

Box plots, also known as box-and-whisker plots, display the distribution of a dataset along a single axis. They show the median, quartiles, and potential outliers in the data.
"""

from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import numpy as np

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target
target_names = iris.target_names

# Box Plot
plt.figure(figsize=(8, 6))
colors = plt.cm.viridis(np.linspace(0, 1, len(target_names)))  # Generate colors from the 'viridis' colormap

for i, species in enumerate(target_names):
    plt.boxplot(X[y == i, 2], positions=[i], widths=0.6, patch_artist=True, boxprops=dict(facecolor=colors[i]))

plt.xlabel('Species')
plt.ylabel('Petal Length (cm)')
plt.title('Box Plot of Petal Length (cm) by Species')
plt.xticks(ticks=np.arange(len(target_names)), labels=target_names)
plt.show()

"""** Interpretation of Box Plot**:
   - This plot summarizes the distribution of petal length for each iris species using a box plot.
   - The x-axis represents the species, and the y-axis represents the petal length in centimeters.
   - The box represents the interquartile range (IQR) of the data, with the median marked by a horizontal line inside the box.
   - The whiskers extend to show the range of the data, excluding outliers.

**7. Violin Plot**

Violin plots are similar to box plots but provide a kernel density estimation of the underlying distribution. They offer a more detailed view of the data's distribution compared to box plots.
"""

# Violin Plot
plt.figure(figsize=(8, 6))
for i, species in enumerate(target_names):
    plt.violinplot(X[y == i, 3], positions=[i], widths=0.6, showmeans=False, showmedians=True)
plt.xlabel('Species')
plt.ylabel('Petal Width (cm)')
plt.title('Violin Plot of Petal Width (cm) by Species')
plt.xticks(ticks=np.arange(len(target_names)), labels=target_names)
plt.show()

"""** Interpretation of Violin Plot**:
   - Similar to the box plot, this plot summarizes the distribution of petal width for each iris species.
   - In addition to the box plot components, the violin plot also includes a rotated kernel density plot on each side, providing a more detailed view of the data distribution.

**8. Histogram**

Histograms display the distribution of a dataset. They group data into bins and show the frequency of occurrences within each bin.
"""

# Histogram
plt.figure(figsize=(8, 6))
plt.hist(X[:, 0], bins=20, alpha=0.6, color='cyan', label='Sepal Length')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Frequency')
plt.title('Histogram of Sepal Length (cm)')
plt.legend()

plt.savefig('histogram.png')
plt.show()

"""**Interpretation of Histogram**:
   - This plot shows the distribution of sepal length using a histogram.
   - The x-axis represents the range of sepal length values, divided into bins, and the y-axis represents the frequency of instances falling into each bin.
   - The bars indicate how many instances have sepal length values within each bin.

"""

from sklearn.datasets import load_iris
import pandas as pd


# Load the Iris dataset
iris = load_iris()

df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

df.to_csv('iris_dataset.csv', index=False)
print('Data save as csv')